#	to re-test all tests when one changed

MAKE := /bin/make

retest-all:
	cd myEnvironment && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myTemp && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
#       errors when running tests  
#	cd mySemantic && $(MAKE) retest && $(MAKE) show-coverage
#	cd ..
	cd myFrame && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
#	errors when running tests
#	cd recursiveDecs && $(MAKE) retest && $(MAKE) show-coverage
#	cd ..
	cd myTranslate && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
#       errors when generating coverage info  
#	cd forChecker && $(MAKE) retest && $(MAKE) show-coverage
#	cd ..
	cd myEscape && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd lexString && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myIRTree && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd addedSemanticChecking && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd lValueTreater && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myComputable && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myEscape && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myMovable && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd typeChecker && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd breakChecker && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myAbstractSyntax && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myControlable && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myMunch && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd mySymbol && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd typeMaker && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd breakGetter && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myCanonical && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myIRTree && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myRegisterAllocation && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myTable && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd stringEscape && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd lexString && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd makeMemory && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myCFGraph && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
	cd myError && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
#   	errors when generating coverage info
#	cd myLiveness && $(MAKE) retest && $(MAKE) show-coverage
#	cd ..
	cd myReport && $(MAKE) retest && $(MAKE) show-coverage
	cd ..
