make-tests:
	cd myEnvironment && $(MAKE)
	cd ..
	cd myTemp && $(MAKE)
	cd ..
#       errors when running tests  
#	cd mySemantic && $(MAKE)
#	cd ..
	cd myFrame && $(MAKE)
	cd ..
#	errors when running tests
#	cd recursiveDecs && $(MAKE)
#	cd ..
	cd myTranslate && $(MAKE)
	cd ..
#       errors when generating coverage info  
#	cd forChecker && $(MAKE)
#	cd ..
	cd myEscape && $(MAKE)
	cd ..
	cd lexString && $(MAKE)
	cd ..
	cd myIRTree && $(MAKE)
	cd ..
	cd addedSemanticChecking && $(MAKE)
	cd ..
	cd lValueTreater && $(MAKE)
	cd ..
	cd myComputable && $(MAKE)
	cd ..
	cd myEscape && $(MAKE)
	cd ..
	cd myMovable && $(MAKE)
	cd ..
	cd typeChecker && $(MAKE)
	cd ..
	cd breakChecker && $(MAKE)
	cd ..
	cd myAbstractSyntax && $(MAKE)
	cd ..
	cd myControlable && $(MAKE)
	cd ..
	cd myMunch && $(MAKE)
	cd ..
	cd mySymbol && $(MAKE)
	cd ..
	cd typeMaker && $(MAKE)
	cd ..
	cd breakGetter && $(MAKE)
	cd ..
	cd myCanonical && $(MAKE)
	cd ..
	cd myIRTree && $(MAKE)
	cd ..
	cd myRegisterAllocation && $(MAKE)
	cd ..
	cd myTable && $(MAKE)
	cd ..
	cd stringEscape && $(MAKE)
	cd ..
	cd lexString && $(MAKE)
	cd ..
	cd makeMemory && $(MAKE)
	cd ..
	cd myCFGraph && $(MAKE)
	cd ..
	cd myError && $(MAKE)
	cd ..
#   	errors when generating coverage info
#	cd myLiveness && $(MAKE)
#	cd ..
	cd myReport && $(MAKE)
	cd ..

clean-tests:
	cd myEnvironment && $(MAKE) clean
	cd ..
	cd myTemp && $(MAKE) clean
	cd ..
#       errors when running tests  
#	cd mySemantic && $(MAKE) clean
#	cd ..
	cd myFrame && $(MAKE) clean
	cd ..
#	errors when running tests
#	cd recursiveDecs && $(MAKE) clean
#	cd ..
	cd myTranslate && $(MAKE) clean
	cd ..
#       errors when generating coverage info  
#	cd forChecker && $(MAKE) clean
#	cd ..
	cd myEscape && $(MAKE) clean
	cd ..
	cd lexString && $(MAKE) clean
	cd ..
	cd myIRTree && $(MAKE) clean
	cd ..
	cd addedSemanticChecking && $(MAKE) clean
	cd ..
	cd lValueTreater && $(MAKE) clean
	cd ..
	cd myComputable && $(MAKE) clean
	cd ..
	cd myEscape && $(MAKE) clean
	cd ..
	cd myMovable && $(MAKE) clean
	cd ..
	cd typeChecker && $(MAKE) clean
	cd ..
	cd breakChecker && $(MAKE) clean
	cd ..
	cd myAbstractSyntax && $(MAKE) clean
	cd ..
	cd myControlable && $(MAKE) clean
	cd ..
	cd myMunch && $(MAKE) clean
	cd ..
	cd mySymbol && $(MAKE) clean
	cd ..
	cd typeMaker && $(MAKE) clean
	cd ..
	cd breakGetter && $(MAKE) clean
	cd ..
	cd myCanonical && $(MAKE) clean
	cd ..
	cd myIRTree && $(MAKE) clean
	cd ..
	cd myRegisterAllocation && $(MAKE) clean
	cd ..
	cd myTable && $(MAKE) clean
	cd ..
	cd stringEscape && $(MAKE) clean
	cd ..
	cd lexString && $(MAKE) clean
	cd ..
	cd makeMemory && $(MAKE) clean
	cd ..
	cd myCFGraph && $(MAKE) clean
	cd ..
	cd myError && $(MAKE) clean
	cd ..
#   	errors when generating coverage info
#	cd myLiveness && $(MAKE) clean
#	cd ..
	cd myReport && $(MAKE) clean
	cd ..


run-tests:
	cd myEnvironment && $(MAKE) show-coverage
	cd ..
	cd myTemp && $(MAKE) show-coverage
	cd ..
#       errors when running tests  
#	cd mySemantic && $(MAKE) show-coverage
#	cd ..
	cd myFrame && $(MAKE) show-coverage
	cd ..
#	errors when running tests
#	cd recursiveDecs && $(MAKE) show-coverage
#	cd ..
	cd myTranslate&& $(MAKE) show-coverage
	cd ..
#       errors when generating coverage info  
#	cd forChecker && $(MAKE) show-coverage
#	cd ..
	cd myEscape && $(MAKE) show-coverage
	cd ..
	cd lexString && $(MAKE) show-coverage
	cd ..
	cd myIRTree && $(MAKE) show-coverage
	cd ..
	cd addedSemanticChecking && $(MAKE) show-coverage
	cd ..
	cd lValueTreater && $(MAKE) show-coverage
	cd ..
	cd myComputable && $(MAKE) show-coverage
	cd ..
	cd myEscape && $(MAKE) show-coverage
	cd ..
	cd myMovable && $(MAKE) show-coverage
	cd ..
	cd typeChecker && $(MAKE) show-coverage
	cd ..
	cd breakChecker && $(MAKE) show-coverage
	cd ..
	cd myAbstractSyntax && $(MAKE) show-coverage
	cd ..
	cd myControlable && $(MAKE) show-coverage
	cd ..
	cd myMunch && $(MAKE) show-coverage
	cd ..
	cd mySymbol && $(MAKE) show-coverage
	cd ..
	cd typeMaker && $(MAKE) show-coverage
	cd ..
	cd breakGetter && $(MAKE) show-coverage
	cd ..
	cd myCanonical && $(MAKE) show-coverage
	cd ..
	cd myIRTree && $(MAKE) show-coverage
	cd ..
	cd myRegisterAllocation && $(MAKE) show-coverage
	cd ..
	cd myTable && $(MAKE) show-coverage
	cd ..
	cd stringEscape && $(MAKE) show-coverage
	cd ..
	cd lexString && $(MAKE) show-coverage
	cd ..
	cd makeMemory && $(MAKE) show-coverage
	cd ..
	cd myCFGraph && $(MAKE) show-coverage
	cd ..
	cd myError && $(MAKE) show-coverage
	cd ..
#   	errors when generating coverage info
#	cd myLiveness && $(MAKE) show-coverage
#	cd ..
	cd myReport && $(MAKE) show-coverage
	cd ..
